// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD06eznlDPyr1qCzFsH0q1N7LVAz7tJSLk',
    appId: '1:552006272364:web:e700b961388810e0751f49',
    messagingSenderId: '552006272364',
    projectId: 'animeshdemo-c5984',
    authDomain: 'animeshdemo-c5984.firebaseapp.com',
    storageBucket: 'animeshdemo-c5984.appspot.com',
    measurementId: 'G-3XS64J3MHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhL_ZIOe0onrD10oetBmCC9Ojohoti4fY',
    appId: '1:552006272364:android:1abcf412ca5c53dc751f49',
    messagingSenderId: '552006272364',
    projectId: 'animeshdemo-c5984',
    storageBucket: 'animeshdemo-c5984.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwEOlmATaUplJYfBhAjSWiqgNgHT9kBZg',
    appId: '1:552006272364:ios:047160aabae06553751f49',
    messagingSenderId: '552006272364',
    projectId: 'animeshdemo-c5984',
    storageBucket: 'animeshdemo-c5984.appspot.com',
    iosClientId: '552006272364-n2l2jj6alhn8ju2f6turkfk85dmgqqin.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwEOlmATaUplJYfBhAjSWiqgNgHT9kBZg',
    appId: '1:552006272364:ios:047160aabae06553751f49',
    messagingSenderId: '552006272364',
    projectId: 'animeshdemo-c5984',
    storageBucket: 'animeshdemo-c5984.appspot.com',
    iosClientId: '552006272364-n2l2jj6alhn8ju2f6turkfk85dmgqqin.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
